title: Digital Methods Accelerator
description: Digital Methods Accelerator overview
baseurl: ""
url: ""
defaults:
  - scope:
      path: "content"
    values:
      layout: page
  - scope:
      path: "content/toolkit"
    values:
      layout: page
      permalink: /toolkit/:basename.html

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .github
