title: 'Digital Methods Accelerator'

# hugo-book theme settings
theme: "hugo-book"
disablePathToLower: false
enableGitInfo: true

params:
  bookLogo: ''
  BookRepo: 'https://github.com/franciscrot/digital-methods-accelerator'
  BookSection: 'toolkit'
  BookCommitPath: 'commit'
  BookEditPath: 'edit/main'
  BookSearch: false
  BookComments: false

outputFormats:
  SearchIndex:
    mediaType: application/json
    baseName: index
    isPlainText: true
    notAlternative: true

outputs:
  home:
    - HTML
    - RSS
    - JSON


# Site menu (add items to generated menu)
menu:
  # before: []
  after:
    - name: "Github"
      url: "https://github.com/franciscrot/digital-methods-accelerator"
      weight: 10


# Tidy up some default hugo site settings
baseURL: 'https://franciscrot.github.io/digital-methods-accelerator/'
uglyurls: true
relativeurls: true
canonifyURLs: false
disableHugoGeneratorInject: true
publishDir: ./public
languageCode: 'en-uk'
# googleanalytics: ''
disableKinds:
  - taxonomy
languages:
  en:
    languageName: English
staticDir:
  - static
